port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:

  - name: Trojan F
    server: 
    port: 443
    type: trojan
    password: 
    network: ws
    sni: 
    skip-cert-verify: true
    udp: true
    ws-opts:
      path: /trojan-ws
      headers:
        Host: 
    
  - name: Vmess
    server: 
    port: 443
    type: vmess
    uuid: 
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: 
    network: ws
    ws-opts:
      path: 
      headers:
        Host: 
    udp: true
  
  - name: Trojan V
    type: vmess
    server: 
    port: 443
    uuid: 
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: 
    network: ws
    ws-path: /vmess-ws
    ws-headers:
      Host: 
proxy-groups:
  - name: Manual Server
    type: select
    proxies:
      - "Best Ping ✓"
      - "Trojan F"
      - "Vmess"
      - "Trojan V"
  - name: Best Ping ✓
    type: url-test
    proxies:
      - "Trojan F"
      - "Vmess"
      - "Trojan V"
    url: https://www.google.com/
    interval: 300
  - name: "LOAD Balance 🌐"
    type: load-balance
    proxies:
      - "Trojan F"
      - "Vmess"
      - "Trojan V"
    url: 'https://www.google.com/'
    interval: 300
rules:
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - IP-CIDR6,fc00::/7,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - IP-CIDR6,fd00::/8,DIRECT,no-resolve
  - DOMAIN-SUFFIX,ad.com,REJECT
  - DOMAIN,analytics.google.com,REJECT
  - DOMAIN,analyticsinsights-pa.googleapis.com,REJECT
  - DOMAIN,analyticsreporting.googleapis.com,REJECT
  - DOMAIN-SUFFIX,doubleclick.net,REJECT
  - DOMAIN-SUFFIX,googleadservices.com,REJECT
  - DOMAIN-SUFFIX,googleadsserving.cn,REJECT
  - DOMAIN-SUFFIX,googlesyndication.com,REJECT
  - DOMAIN-SUFFIX,googletagmanager.com,REJECT
  - DOMAIN-SUFFIX,googletagservices.com,REJECT
  - DOMAIN-SUFFIX,google-analytics.com,REJECT
  - DOMAIN-KEYWORD,adservice,REJECT
  - DOMAIN-KEYWORD,analytics,REJECT
  - DOMAIN-KEYWORD,analysis,REJECT
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - GEOIP,IR,DIRECT
  - MATCH,, Manual Server , LOAD Balance 🌐, dns-failed

